# Generated by Django 4.2.29 on 2026-03-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Messages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sender", models.CharField(max_length=20)),
                ("email", models.CharField(max_length=20)),
                ("message", models.CharField(max_length=500)),
                (
                    "priority",
                    models.IntegerField(
                        choices=[(1, "Low"), (2, "Meduim"), (3, "High")]
                    ),
                ),
            ],
        ),
    ]
