# Generated by Django 4.2.29 on 2026-03-12 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_project_delete_messages"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
            ],
        ),
    ]
