name: Build and deploy Python app to Azure Web App - portfolio-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies into project folder
        run: |
          cd server/portfolio_server
          rm -rf venv antenv
          pip install -r requirements.txt --target=".python_packages/lib/site-packages"
          du -sh .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B918917145BC4F51B2846B919ED5A95C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7DAECB7AF83E40709ECA723B9C30832B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A8F28C4C6F24415CA9620BDACE09DD5C }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'portfolio-backend'
          slot-name: 'Production'
          package: server/portfolio_server